export { default as LightThemeIcon } from './icons/theme-light.svg'
export { default as DarkThemeIcon } from './icons/theme-dark.svg'
export { default as AboutIcon } from './icons/about-20-20.svg'
export { default as MainIcon } from './icons/main-20-20.svg'
export { default as ProfileIcon } from './icons/profile-20-20.svg'
